// Часть проекта Firework с открытым исходным кодом.
// Лицензия EPL 2.0, подробнее в файле LICENSE. Copyright (c) 2026 Firework

/// > ENG: Implements commands for sending to an adapter function pointer, does not use 
/// heap-allocated types. The adapter allows implementing an abstraction over.
/// When writing your own adapter, you must implement a match or another way to 
/// iterate over possible commands, after which return one of the variants in the 
/// AdapterResult enum. The adapter is designed to interact with the window, rendering,
/// and the OS. The adapter works with handles (usize wrapper) for objects, textures,
/// fonts and other entities that are created via AdapterCommand. The framework itself 
/// and code generation are completely isolated from rendering and native calls
/// > RU: Реализует команды для отправки в указатель на функцию адаптера, не использует типы
/// которые хранятся в куче. Адаптер позволяет реализовать абстракцию над. При написании
/// своего адаптера вы должны реализовать match или другой способ прохода по возможным
/// командам, после чего вернуть один из вариантов в перечислении AdapterResult. Адаптер
/// пишется для взаимодействия с окном, рендерингом и ОС. Сам фреймворк и кодогенерация
/// полностью изолирована от работы с рендерингом и нативными вызовами. Адаптер работает
/// с хэндлами или же id (usize обёртка) для объектов, текстур, шрифтов и т.д. которые
/// создаются через AdapterCommand
#[derive(Debug, Clone, Copy)]
pub enum AdapterCommand {
    /// > ENG: This command deletes all render objects currently existing on the screen.
    /// This command must synchronously (within 1 frame) iterate over all objects
    /// that have been created and received an AdapterHandleObject (Textures and fonts
    /// do not receive AdapterHandleObject and therefore should not be deleted.
    /// This command is only for render objects that the user sees on the screen).
    /// The framework will call this command in code generated by the macro during
    /// navigation to clear all objects created by the previous screen.
    /// The RemoveAll call must be safe, use an ID reincarnation system if using
    /// the heap to avoid reallocations. Do not allow panics when using the command.
    /// Instead of clearing the object storage, it is recommended to carefully delete
    /// them one by one and mark the ID as dead so that its place can be taken by
    /// other objects. This is also useful for array-based storage since in that case
    /// you will store the array on the stack or in BSS/
    /// > RU: Эта команда выполняет удаление всех рендер объектов которые существуют сейчас на
    /// экране. Эта команда должна синхронно (за 1 кадр) пройтись по всем объектам которые
    /// созданы и получили AdapterHandleObject (Текстуры и шрифты не AdapterHandleObject 
    /// поэтому они не должны удаляться. Эта команда только для рендер объектов которые
    /// пользователь видит на экране). Фреймворк будет вызывать эту команду в сгенерированном
    /// макросом коде при навигации чтобы очистить все объекты которые были созданы предыдущим
    /// экраном. Вызов RemoveAll должен быть безопасным, используйте систему реинкарнации ID 
    /// если используйте кучу чтобы не вызывать реаллокации. Не допускайте паник при
    /// использовании команды, вместо очищения хранилища объектов рекомендуется осторожно
    /// их удалять по одному и записывать id как мёртвый чтобы его место заняли другие объекты.
    /// Это также полезно при хранилище на основе массива так как в таком случае вы будете
    /// хранить массив на стэке или в BSS
    RemoveAll,

    RunLoop {
        title: &'static str,
        width: u32,
        height: u32,
        listener: fn(AdapterEvent),
    }
}

/// > ENG: Enumeration for implementing an abstraction over the EventLoop event. In your 
/// adapter implementation, you use any crate to implement windowing (or JS Event Loop or 
/// native  system loop) and send events to the listener closure that the framework provides 
/// for event processing.
/// > RU: Перечисления для реализации абстракции над событием EventLoop. В своей реализации
/// адаптера вы используете любой крейт для реализации работы с окном (или JS Event Loop или
/// нативным лупом системы) и отправляете в замыкание listener которое передаёт фреймворк для
/// обработки событий
#[derive(Debug, Clone, Copy)]
pub enum AdapterEvent {
    /// > ENG: Screen click in x (u32), y (u32) format. The specification tries not to use 
    /// f32 because Firework must support embedded devices in addition to mobile and desktop.
    /// Must be called. The third argument is the click phase.
    /// > RU: Клик по экрану в формате x (u32), y (u32). Спецификация старается не использовать
    /// f32 так как кроме мобильных и декстопных устройств Firework должен поддерживать
    /// embedded. Нужно вызывать. Третий аргумент это фаза клика
    Touch(u32, u32, AdapterClickPhase),

    /// > ENG: Keyboard input. The argument is the character code that was typed.
    /// > RU: Ввод с клавиатуры. Аргумент это код символа который был набран
    Key(u32),

    /// > ENG: Must be called every frame.
    /// > RU: Должен вызываться каждый кадр
    Tick,

    /// > ENG: Request to close the application
    /// > RU: Запрос на закрытие приложения
    CloseRequest,
}

/// > ENG: Enumeration for specifying the screen click phase.
/// > RU: Перечисление для указания фазы клика по экрану
#[derive(Debug, Clone, Copy)]
pub enum AdapterClickPhase {
    /// > ENG: Finger just pressed and is holding.
    /// > RU: Палец только нажал и держит
    Began,
    
    /// > ENG: Finger pressed (Began) and is moving across the screen.
    /// > RU: Палец нажал (Began) и водит по экрану
    Moved,

    /// > ENG: Finger was released.
    /// > RU: Палец отпустил
    Ended,

    /// > ENG: Click was cancelled.
    /// > RU: Отмена клика
    Cancelled,
}

#[derive(Debug, Clone, Copy)]
pub enum AdapterResult {
    Void,
    Fail,
}
