// Часть проекта Firework с открытым исходным кодом.
// Лицензия EPL 2.0, подробнее в файле LICENSE. Copyright (c) 2026 Firework

use super::*;

/// Принимает выражение и возвращает его атрибуты
pub fn get_expr_attrs(expr: &Expr) -> &[Attribute] {
    match expr {
        Expr::Array(expr_array) => &expr_array.attrs,
        Expr::Assign(expr_assign) => &expr_assign.attrs,
        Expr::Async(expr_async) => &expr_async.attrs,
        Expr::Await(expr_await) => &expr_await.attrs,
        Expr::Binary(expr_binary) => &expr_binary.attrs,
        Expr::Block(expr_block) => &expr_block.attrs,
        Expr::Break(expr_break) => &expr_break.attrs,
        Expr::Call(expr_call) => &expr_call.attrs,
        Expr::Cast(expr_cast) => &expr_cast.attrs,
        Expr::Closure(expr_closure) => &expr_closure.attrs,
        Expr::Const(expr_const) => &expr_const.attrs,
        Expr::Continue(expr_continue) => &expr_continue.attrs,
        Expr::Field(expr_field) => &expr_field.attrs,
        Expr::ForLoop(expr_for_loop) => &expr_for_loop.attrs,
        Expr::Group(expr_group) => &expr_group.attrs,
        Expr::If(expr_if) => &expr_if.attrs,
        Expr::Index(expr_index) => &expr_index.attrs,
        Expr::Infer(expr_infer) => &expr_infer.attrs,
        Expr::Let(expr_let) => &expr_let.attrs,
        Expr::Lit(expr_lit) => &expr_lit.attrs,
        Expr::Loop(expr_loop) => &expr_loop.attrs,
        Expr::Macro(expr_macro) => &expr_macro.attrs,
        Expr::Match(expr_match) => &expr_match.attrs,
        Expr::MethodCall(expr_method_call) => &expr_method_call.attrs,
        Expr::Paren(expr_paren) => &expr_paren.attrs,
        Expr::Path(expr_path) => &expr_path.attrs,
        Expr::Range(expr_range) => &expr_range.attrs,
        Expr::RawAddr(expr_raw_addr) => &expr_raw_addr.attrs,
        Expr::Reference(expr_reference) => &expr_reference.attrs,
        Expr::Repeat(expr_repeat) => &expr_repeat.attrs,
        Expr::Return(expr_return) => &expr_return.attrs,
        Expr::Struct(expr_struct) => &expr_struct.attrs,
        Expr::Try(expr_try) => &expr_try.attrs,
        Expr::TryBlock(expr_try_block) => &expr_try_block.attrs,
        Expr::Tuple(expr_tuple) => &expr_tuple.attrs,
        Expr::Unary(expr_unary) => &expr_unary.attrs,
        Expr::Unsafe(expr_unsafe) => &expr_unsafe.attrs,
        Expr::While(expr_while) => &expr_while.attrs,
        Expr::Yield(expr_yield) => &expr_yield.attrs,
        Expr::Verbatim(_) => &[],
        _ => &[],
    }
}

/// Принимает мутабельную ссылку на выражение и возвращает мутабельную ссылку на атрибут
pub fn get_expr_attrs_mut(expr: &mut Expr) -> Option<&mut Vec<Attribute>> {
    match expr {
        Expr::Array(expr_array) => Some(&mut expr_array.attrs),
        Expr::Assign(expr_assign) => Some(&mut expr_assign.attrs),
        Expr::Async(expr_async) => Some(&mut expr_async.attrs),
        Expr::Await(expr_await) => Some(&mut expr_await.attrs),
        Expr::Binary(expr_binary) => Some(&mut expr_binary.attrs),
        Expr::Block(expr_block) => Some(&mut expr_block.attrs),
        Expr::Break(expr_break) => Some(&mut expr_break.attrs),
        Expr::Call(expr_call) => Some(&mut expr_call.attrs),
        Expr::Cast(expr_cast) => Some(&mut expr_cast.attrs),
        Expr::Closure(expr_closure) => Some(&mut expr_closure.attrs),
        Expr::Const(expr_const) => Some(&mut expr_const.attrs),
        Expr::Continue(expr_continue) => Some(&mut expr_continue.attrs),
        Expr::Field(expr_field) => Some(&mut expr_field.attrs),
        Expr::ForLoop(expr_for_loop) => Some(&mut expr_for_loop.attrs),
        Expr::Group(expr_group) => Some(&mut expr_group.attrs),
        Expr::If(expr_if) => Some(&mut expr_if.attrs),
        Expr::Index(expr_index) => Some(&mut expr_index.attrs),
        Expr::Infer(expr_infer) => Some(&mut expr_infer.attrs),
        Expr::Let(expr_let) => Some(&mut expr_let.attrs),
        Expr::Lit(expr_lit) => Some(&mut expr_lit.attrs),
        Expr::Loop(expr_loop) => Some(&mut expr_loop.attrs),
        Expr::Macro(expr_macro) => Some(&mut expr_macro.attrs),
        Expr::Match(expr_match) => Some(&mut expr_match.attrs),
        Expr::MethodCall(expr_method_call) => Some(&mut expr_method_call.attrs),
        Expr::Paren(expr_paren) => Some(&mut expr_paren.attrs),
        Expr::Path(expr_path) => Some(&mut expr_path.attrs),
        Expr::Range(expr_range) => Some(&mut expr_range.attrs),
        Expr::RawAddr(expr_raw_addr) => Some(&mut expr_raw_addr.attrs),
        Expr::Reference(expr_reference) => Some(&mut expr_reference.attrs),
        Expr::Repeat(expr_repeat) => Some(&mut expr_repeat.attrs),
        Expr::Return(expr_return) => Some(&mut expr_return.attrs),
        Expr::Struct(expr_struct) => Some(&mut expr_struct.attrs),
        Expr::Try(expr_try) => Some(&mut expr_try.attrs),
        Expr::TryBlock(expr_try_block) => Some(&mut expr_try_block.attrs),
        Expr::Tuple(expr_tuple) => Some(&mut expr_tuple.attrs),
        Expr::Unary(expr_unary) => Some(&mut expr_unary.attrs),
        Expr::Unsafe(expr_unsafe) => Some(&mut expr_unsafe.attrs),
        Expr::While(expr_while) => Some(&mut expr_while.attrs),
        Expr::Yield(expr_yield) => Some(&mut expr_yield.attrs),
        Expr::Verbatim(_) => None,
        _ => None,
    }
}
